### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: damo/cv_unet_person-image-cartoon-3d_compound-models/cartoon_anime_h.pb; No such file or directory

### ISSUE THREAD

**Issue by yaohwang** [menyifang/DCT-Net#28]
when running `python multi-style/run.py --style 3d` I get

```
Traceback (most recent call last):
  File "multi-style/run.py", line 46, in <module>
    process(args)
  File "multi-style/run.py", line 17, in process
    algo = Cartoonizer(dataroot='damo/cv_unet_person-image-cartoon-3d_compound-models')
  File "./source/cartoonize.py", line 19, in __init__
    os.path.join(dataroot, 'cartoon_anime_h.pb'), 'model_head')
  File "./source/cartoonize.py", line 38, in load_sess
    graph_def.ParseFromString(f.read())
  File "/root/miniconda3/envs/python-app/lib/python3.7/site-packages/tensorflow_core/python/lib/io/file_io.py", line 122, in read
    self._preread_check()
  File "/root/miniconda3/envs/python-app/lib/python3.7/site-packages/tensorflow_core/python/lib/io/file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: damo/cv_unet_person-image-cartoon-3d_compound-models/cartoon_anime_h.pb; No such file or directory
```

**Comment by ZJ-CAI** [comment]
manully change the file name from cartoon_h.pb to cartoon_anime_h.pb
