### ISSUE TITLE
multi-style/download error

### ISSUE THREAD

**Issue by kitterive** [menyifang/DCT-Net#30]
root@0c1b63d9300d:~/project/mydev/DCT-Net# python multi-style/download.py --style 3d
download 3d model
2023-02-09 09:06:57,604 - modelscope - INFO - Model revision not specified, use the latest revision: v1.0.0
2023-02-09 09:06:57,884 - modelscope - INFO - downloading http://www.modelscope.cn/api/v1/models/damo/cv_unet_person-image-cartoon-3d_compound-models/repo?Revision=v1.0.0&FilePath=alpha.jpg to /root/project/mydev/DCT-Net/temp/tmpxiw9k_fi/tmpv1togmif
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.52k/2.52k [00:00<00:00, 6.67MB/s]
2023-02-09 09:06:57,936 - modelscope - INFO - storing http://www.modelscope.cn/api/v1/models/damo/cv_unet_person-image-cartoon-3d_compound-models/repo?Revision=v1.0.0&FilePath=alpha.jpg in cache at ./temp/tmpxiw9k_fi
2023-02-09 09:06:57,936 - modelscope - ERROR - File ./temp/tmpxiw9k_fi/alpha.jpg integrity check failed, the download may be incomplete, please try again.
Traceback (most recent call last):
  File "multi-style/download.py", line 35, in <module>
    process(args)
  File "multi-style/download.py", line 13, in process
    model_dir = snapshot_download('damo/cv_unet_person-image-cartoon-3d_compound-models', cache_dir='.')
  File "/opt/conda/lib/python3.7/site-packages/modelscope/hub/snapshot_download.py", line 146, in snapshot_download
    file_integrity_validation(temp_file, model_file[FILE_HASH])
  File "/opt/conda/lib/python3.7/site-packages/modelscope/hub/utils/utils.py", line 94, in file_integrity_validation
    raise FileIntegrityError(msg)
modelscope.hub.errors.FileIntegrityError: File ./temp/tmpxiw9k_fi/alpha.jpg integrity check failed, the download may be incomplete, please try again.

**Comment by kitterive** [comment]
solved
