### ISSUE TITLE
error after python run_sdk.py

### ISSUE THREAD

**Issue by zarkua** [menyifang/DCT-Net#8]
2022-08-11 12:29:20,507 - modelscope - WARNING - ('PIPELINES', 'image-portrait-stylization', 'unet-person-image-cartoon') not found in ast index file
Traceback (most recent call last):
  File "run_sdk.py", line 5, in <module>
    img_cartoon = pipeline(Tasks.image_portrait_stylization, 'damo/cv_unet_person-image-cartoon_compound-models')
  File "C:\Users\George\anaconda3\envs\dctnet\lib\site-packages\modelscope\pipelines\builder.py", line 250, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "C:\Users\George\anaconda3\envs\dctnet\lib\site-packages\modelscope\pipelines\builder.py", line 162, in build_pipeline
    return build_from_cfg(
  File "C:\Users\George\anaconda3\envs\dctnet\lib\site-packages\modelscope\utils\registry.py", line 197, in build_from_cfg
    raise KeyError(f'{obj_type} is not in the {registry.name}'
KeyError: 'unet-person-image-cartoon is not in the pipelines registry group image-portrait-stylization'

**Comment by menyifang** [comment]
I reinstall pkgs and run run_sdk.py, everything goes well. It seems modelscope not correctly installed.

**Comment by zarkua** [comment]
@menyifang sorry, seems like i have the same mistake after reinstallation of tensorflow and modelscope.

**Comment by zarkua** [comment]
i`ve reinstalled everything including conda env - still the same error. Maybe i need specific version of tensorflow?

**Comment by menyifang** [comment]
can you download the model binary (*.pb) from modelscope? If so, you can also run from source code with downloaded files.

**Comment by zarkua** [comment]
they are downloadable, but when i try to run.py I have

(dctnet) PS C:\DCT-Net> python run.py
>>
2022-08-14 19:54:37,580 - modelscope - INFO - PyTorch version 1.12.1 Found.
2022-08-14 19:54:37,584 - modelscope - INFO - TensorFlow version 2.9.1 Found.
2022-08-14 19:54:37,584 - modelscope - INFO - Loading ast index from C:\Users\George/.cache\modelscope\ast_indexer
2022-08-14 19:54:37,589 - modelscope - INFO - Loading done! Current index file version is 0.3.4, with md5 d41d8cd98f00b204e9800998ecf8427e
2022-08-14 19:54:39.214081: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-08-14 19:54:43.809963: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1638 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
2022-08-14 19:54:44.073478: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1638 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
2022-08-14 19:54:44.304234: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1638 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
loading model from damo/cv_unet_person-image-cartoon_compound-models\cartoon_anime_h.pb
WARNING:tensorflow:From C:\DCT-Net\source\cartoonize.py:36: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
2022-08-14 19:54:44.419941: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
load model damo/cv_unet_person-image-cartoon_compound-models\cartoon_anime_h.pb done.
2022-08-14 19:54:44.459885: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1638 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
loading model from damo/cv_unet_person-image-cartoon_compound-models\cartoon_anime_bg.pb
load model damo/cv_unet_person-image-cartoon_compound-models\cartoon_anime_bg.pb done.
Could not load library cudnn_ops_infer64_8.dll. Error code 126
Please make sure cudnn_ops_infer64_8.dll is in your library path!

**Comment by woctezuma** [comment]
> Could not load library cudnn_ops_infer64_8.dll. Error code 126
> Please make sure cudnn_ops_infer64_8.dll is in your library path!
